services:
  - type: web
    name: job-portal-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVarGroups: []
    envVars:
      - key: NODE_ENV
        value: production
